# Generated by Django 2.1.7 on 2019-12-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10)),
                ('sage', models.IntegerField()),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
            },
        ),
    ]
